name: Daily Competitor Monitor

on:
  schedule:
    # 1. 아침 8시 수령 목표 -> 한국 시간 07:44 시작 (UTC 22:44)
    - cron: '44 22 * * *'
    # 2. 오후 3시 수령 목표 -> 한국 시간 14:44 시작 (UTC 05:44)
    - cron: '44 5 * * *'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Libraries
        run: pip install -r requirements.txt
        
      - name: Run Crawler Script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
      - name: Upload Debug Screenshots
      if: always()  # 에러가 나도 무조건 실행
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshots
        path: docs/reports/*.png  # 이 경로에 있는 png 파일을 저장함
      - name: Commit and Push Results
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add data/ docs/
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m "Update Report: $(date +'%Y-%m-%d %H:%M:%S')"
          
          git pull --rebase
          git push
